version: '3.8'

services:

  dstoolbox:
    image: josealvaradoguzman/data-science-toolbox
    networks:
        - net
    ports:
        - 8887:8888
    links:
        - neo4j:neo4jdb
    
  neo4j:
    image: josealvaradoguzman/neo4j-graph-datascience
    environment:
      NEO4J_dbms_memory_pagecache_size: "6G"
      NEO4J_dbms_memory_heap_initial__size: "4G"
      NEO4J_dbms_memory_heap_max__size: "4G"
      NEO4J_dbms_connector_bolt_advertised__address: ":7686"
      NEO4JLABS_PLUGINS: '["apoc","graph-data-science"]'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_gds_model_store__location: "/var/lib/neo4j/gds/models"
      NEO4J_gds_enterprise_license__file: "/var/lib/neo4j/licenses/gds_license.txt"
      NEO4J_dbms_allow__upgrade: "true"
      USER: "neo4j"
      PASSWORD: "Neo4jL3tM31n!"
      DATABASE: amlfraud
      NEO4J_AUTH: neo4j/Neo4jL3tM31n!
    networks:
        - net
    ports:
        - 7473:7474
        - 7686:7687   

networks:
  net:
