version: '3'

services:

  dstoolbox:
    image: josealvaradoguzman/data-science-toolbox
    networks:
        - net
    ports:
        - 8887:8888
    links:
        - neo4j:neo4jdb
    
  neo4j:
    image: josealvaradoguzman/neo4j-graph-datascience
    networks:
        - net
    ports:
        - 7473:7474
        - 7686:7687   
    volumes:
        - ds-bootcamp-data:/data/databases
       
  data:
    image: josealvaradoguzman/data-science-bootcamp-data
    volumes:
        - ds-bootcamp-data:/data
networks:
  net:

volumes:
  ds-bootcamp-data:
