version: '3.8'

services:

  data:
    image: josealvaradoguzman/data-science-bootcamp-data
    volumes:
        - ds-bootcamp-data:/data

  dstoolbox:
    image: josealvaradoguzman/data-science-toolbox
    networks:
        - net
    ports:
        - 8887:8888
    links:
        - neo4j:neo4jdb
    volumes:
        - ds-bootcamp-data:/data
    
  neo4j:
    image: neo4j:4.3.5-enterprise
    environment:
      NEO4J_dbms_memory_pagecache_size: "2G"
      NEO4J_dbms_memory_heap_initial__size: "2G"
      NEO4J_dbms_memory_heap_max__size: "2G"
      NEO4J_dbms_connector_bolt_advertised__address: ":7686"
      NEO4JLABS_PLUGINS: '["apoc","graph-data-science"]'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_dbms_allow__upgrade: "true"
      NEO4J_AUTH: neo4j/DS_Training
    networks:
        - net
    ports:
        - 7473:7474
        - 7686:7687   
    volumes:
        - ds-bootcamp-data:/var/lib/neo4j/data
    depends_on:
        - data
       
networks:
  net:

volumes:
  ds-bootcamp-data:
