version: '3'

services:

  dstoolbox:
      image: josealvaradoguzman/data-science-toolbox
      networks:
          - net
      ports:
          - 8887:8888
    
  neo4j:
      image: josealvaradoguzman/neo4j-graph-datascience
      networks:
          - net
      ports:
          - 7473:7474
          - 7686:7687   
  data:
    image: josealvaradoguzman/paysim-dataset
    volumes:
          - paysim-data:/data
networks:
  net:

volumes:
  paysim-data:
